import { RestEndpointMethodTypes } from "@octokit/rest";

export type GithubUser = RestEndpointMethodTypes["users"]["getAuthenticated"]["response"]["data"];

/*
{
  login: "priolo",
  id: 402921,
  node_id: "MDQ6VXNlcjQwMjkyMQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/402921?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/priolo",
  html_url: "https://github.com/priolo",
  followers_url: "https://api.github.com/users/priolo/followers",
  following_url: "https://api.github.com/users/priolo/following{/other_user}",
  gists_url: "https://api.github.com/users/priolo/gists{/gist_id}",
  starred_url: "https://api.github.com/users/priolo/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/priolo/subscriptions",
  organizations_url: "https://api.github.com/users/priolo/orgs",
  repos_url: "https://api.github.com/users/priolo/repos",
  events_url: "https://api.github.com/users/priolo/events{/privacy}",
  received_events_url: "https://api.github.com/users/priolo/received_events",
  type: "User",
  user_view_type: "private",
  site_admin: false,
  name: null,
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  notification_email: null,
  public_repos: 37,
  public_gists: 1,
  followers: 2,
  following: 2,
  created_at: "2010-09-16T16:54:37Z",
  updated_at: "2025-12-13T12:40:38Z",
  private_gists: 3,
  total_private_repos: 5,
  owned_private_repos: 5,
  disk_usage: 51052,
  collaborators: 0,
  two_factor_authentication: true,
  plan: {
    name: "free",
    space: 976562499,
    collaborators: 0,
    private_repos: 10000,
  },
}
  */